### ISSUE TITLE
Lead flood

### ISSUE THREAD

**Issue by soulseekah** [soulseekah/Gravity-Forms-Saved-Forms-Addon#12]
Each save creates a new lead. This appears to have unwanted consequences. Needs more research and a good solution.

**Comment by alisalama** [comment]
Hi,

Great plugin, but I'm using it in a project and I'm seeing similar issues.

Every time there is a 'Save', two leads are generated, and therefore two notification emails go out. Neither of which are ideal.

If I remove this line it does seems to work fine...
 ```PHP
GFFormDisplay::process_form( $form_id );
 ```

But I'm wondering if there are any further implications if I do that?

Cheers

**Comment by soulseekah** [comment]
Are you using the latest master.zip version? https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/archive/master.zip

Cause this was fixed in https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/commit/24121c0ddafb23608a840696cc7e381004a435c1

**Comment by alisalama** [comment]
Yeah, I'm using 4.3.1.

I thought it was maybe something I had done, or a plugin conflict or something, so created a fresh wordpress install, latest gravity forms, one simple form and was still having the issue.

Am I misunderstanding? Is it supposed to save twice for some reason?

**Comment by soulseekah** [comment]
I'm talking about the version of this addon. The Gravity-Forms-Saved-Forms-Addon are you using this download https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/archive/master.zip to get it?

**Comment by alisalama** [comment]
Yeah I am.

**Comment by alisalama** [comment]
Just wondering if you have any idea of the reason why this happens?

**Comment by soulseekah** [comment]
Are you positively sure you're using the latest version of my plugin (download https://github.com/soulseekah/Gravity-Forms-Saved-Forms-Addon/archive/master.zip)? Because this issue was raised and fixed in March.

**Comment by alisalama** [comment]
Yeah definitely. I swapped to the one you just sent, same issue. Then I did a comparison of the two folders (one you sent and one I was using) just to be sure, and they are identical.

I've included the Gravity form log, you can clearly see it creating two leads.
http://pastebin.com/9Y0YtFu2

**Comment by soulseekah** [comment]
Err, can you check whether you have the option "Send on save" in the Form Settings checked?

**Comment by alisalama** [comment]
Yeah it is set to true.

**Comment by soulseekah** [comment]
You should uncheck that button if you don't want notifications of saved forms being sent out.

**Comment by alisalama** [comment]
I see. My issue is more that it is generating two leads, and even if I uncheck that it still generates twice? Obviously this isn't that efficient, I'm looking at a fairly large number of records so doubling that could have a large impact.

So the design is to generate it twice?

**Comment by soulseekah** [comment]
All the partial generated leads have a status of 'pending' and should not be triggering any notifications (unless "Send on save" is checked). The design is to generate as many pending leads as there are "saves" on a form. If you save the form 7 times you'll have 7 pending leads.

There is, however, a cleanup function that allows you to remove all pending leads in one go on the "pending completed entries" screen. You just hit that button and all incomplete saved forms are removed.

As for the bug with a notification still being sent, please send me the latest version of Gravity Forms to gennady[at]kovshenin[dot]com and I'll try to take a look at it in the coming weeks, and if I'm able to reproduce the issue I'll gladly fix it.

**Comment by alisalama** [comment]
I see. The issue that is occuring is that if I save the form 7 times, I see 14 pending leads in the database.

See attached screenshot. Two leads created automatically on 1 save, and both tagged as pending.

<img width="1368" alt="localhost___localhost___wordpressoriginal___wp_rg_lead_meta___phpmyadmin_4_2_10_and_wordpress_wp-content_uploads_gravity_forms_logs_gravityforms_txt" src="https://cloud.githubusercontent.com/assets/7068759/10914879/325a566c-824c-11e5-81b9-09b7d919e7fb.png">

If I remove the line...
 ```PHP
GFFormDisplay::process_form( $form_id );
 ```

... then it works fine? Is there any reason not to do this, or is this a fix?

**Comment by soulseekah** [comment]
I'll let you know within a couple of weeks hopefully, that function there is for multipage support; if you remove it multipage forms will not be saved correctly. You have to remember that this plugin is one big hack, because Gravity Forms is so awkwardly designed it's really tough to get it going. It worked perfectly fine on some versions, then once a release is rolled out it stops working. I hate Gravity Forms, seriously.

**Comment by alisalama** [comment]
Thanks, I'm finding the same. I've built a fairly extensive application based upon gravity forms, and although the back end form builder side is great, it is causing me a few issues on the front end.

Thanks again for your help.

**Comment by alisalama** [comment]
Ok, spent a bit of time tracing it through, and have a slightly less 'hacky' fix (still a bit hacky but better), than just commenting out the process_form call.

I figured out it is saving two leads because there is an 'init' hook in the gravityforms.php which is called after the first lead is submitted, which runs through the whole form submission process a second time and as result submits twice.

The function (maybe_process_form) that it hooks in to has this check at the top, though so if it fails on the second loop through then it won't be processed. 

```PHP
$form_id = isset( $_POST['gform_submit'] ) ? absint( $_POST['gform_submit'] ) : 0;
if ( $form_id ) {
    ...
}
```

So, after the form has been processed in maybe_save_confirmation, just set it to fail the check...
```PHP
/* Spoof the page number and make-believe */
$_POST[ "gform_target_page_number_{$form_id}" ] = 65535;
require_once( GFCommon::get_base_path() . '/form_display.php' );
GFFormDisplay::process_form( $form_id );

/* Set the second form being submitted so the second attempt fails */
$_POST['gform_submit'] = 0;
```

Seems to work fine.

**Comment by soulseekah** [comment]
I looked at Gravity Forms 1.9 and they introduced a "Save and Continue" feature. I think that there's no point in trying to fix this plugin, but rather leverage their Save and Continue mechanisms to provide form states, restores, notifications.

I'm closing this issue as no longer valid as of GF 1.9.

Thank you for your input.

**Comment by soulseekah** [comment]
e4ed4c0f4f8191b6af7f791c3aad5501a3e86a2d fixes the above issues and becomes less hacky and dirty thanks to the new "Save and Continue" feature in Gravity Forms 1.9
